### ISSUE TITLE
Mechanics advice

### ISSUE THREAD

**Issue by Forerunner16** [AspectsLove/spicychickenquest#2]
When you see floor markers going in one direction, it means your character will be flung in that direction against your will (unless you use Arm’s Length or Surecast)

I would add about knockbacks that arms length/surecast do not work on.

Also, you have chains as being always go apart to break, some are go together, like o12s (has both types), gilgamesh 2, ifrit chains

**Comment by sudomistress** [comment]
Good feedback. This gives me a few bits of ideas. 

Something I want to consider is by default what should you do if you see a mechanic. Special types of tethers for specific fights will have a unique mechanic which I feel works best in the individual guides for those specific fights. 

And where Arm's Length and Surecast do not work, I think that's also rather fight specific. But I can make mention that it will not work on all fights.  This is awesome! 

Thanks Fore!
